#!/usr/bin/env zsh
# set -x
autoload -U colors &> /dev/null 
colors &> /dev/null 
export T4D_ROOT_PATH="${T4D_ROOT_PATH:-$HOME/.tools4dev}"
export Tools4Dev_PATH="${Tools4Dev_PATH:-$T4D_ROOT_PATH/src}"
function t4d-init() { source $T4D_ROOT_PATH/init }

if [[ -e "$Tools4Dev_PATH/manifest.xml" ]]; then
    export WS_TEAM="$(cat $Tools4Dev_PATH/manifest.xml | grep '<team' | grep -Eo 'name=.*' | cut -d '"' -f2)"
fi

export T4D_SILENT_COMMAND=true

case $1 in
    team)
        t4d-init &> /dev/null
        if [[ "$2" == "-add" ]]; then
            _TeamOriginalPath="$PWD"
            if [[ -e "$_TeamOriginalPath/t4d-manifest.xml" ]]; then
                export WS_TEAM="$(cat $_TeamOriginalPath/t4d-manifest.xml | grep '<team' | grep -Eo 'name=.*' | cut -d '"' -f2)"
                if [[ ! -e "$Tools4Dev_PATH/Team/$WS_TEAM" ]]; then
                    ln -sfn $_TeamOriginalPath $Tools4Dev_PATH/Team/$WS_TEAM
                    ln -sfn $_TeamOriginalPath/t4d-manifest.xml $Tools4Dev_PATH/manifest.xml
                    _t4dCheckSucceeded "Team $WS_TEAM added to Tools4Dev"
                    _t4dDebugLog $pinfo "you can now use wkd to reload your environment"
                else
                    _t4dCheckInfo "Team $WS_TEAM already exist"
                fi
            else
                _t4dDebugLog $perror "Folder >$_TeamOriginalPath< does not contain t4d-manifest.xml"
            fi
        else
            local _TeamOriginalPath="$(readlink $Tools4Dev_PATH/Team/$2)"
            if [[ "$_TeamOriginalPath" == "" ]]; then
                _TeamOriginalPath="$Tools4Dev_PATH/Team/$2"
            fi
            if [[ -e "$_TeamOriginalPath/t4d-manifest.xml" ]] && [[ "$WS_TEAM" != "$2" ]]; then
                ln -sfn $_TeamOriginalPath/t4d-manifest.xml $Tools4Dev_PATH/manifest.xml
                _t4dDebugLog $plog "Tools4Dev is now linked to $2"
                _t4dDebugLog $plog "Team folder is now $_TeamOriginalPath"
                _t4dDebugLog $pinfo "you can now use wkd to reload your environment"
            elif [[ "$WS_TEAM" == "$2" ]]; then
                _t4dCheckSucceeded "Team $2 already setup in Tools4Dev"
            fi
        fi
        
    ;;
    update)
        set -e
        shift
        t4d-init &> /dev/null || t4d-init
        # t4dLoadProjectConf &> /dev/null
        t4dUpdate ${@}
    ;;
    clone)
        set -e
        shift
        cd $Tools4Dev_PATH
        t4d-init &> /dev/null || t4d-init
        # t4dLoadProjectConf &> /dev/null
        t4dUpdate ${@}
        wks clone
    ;;
    exec)
        set -e
        if [[ -e $PWD/project.env ]]; then
            source $PWD/project.env &> /dev/null
        else
            source $Tools4Dev_PATH/tools4Dev.env &> /dev/null
        fi
        t4dLoadProjectConf &> /dev/null || t4dLoadProjectConf
        $@
    ;;
    docker)
        shift
        cd $Tools4Dev_PATH 
        mkdir -p $Tools4Dev_PATH/.t4d
        if [[ -e "$Tools4Dev_PATH/.t4d/.containerID" ]]; then
            T4D_CONTAINER_ID="$(cat $Tools4Dev_PATH/.t4d/.containerID)"
        fi
        case $1 in
            build)
                echo "docker build -t t4d ."
                docker build -t t4d .
            ;;
            run)
                docker run -dt t4d > $Tools4Dev_PATH/.t4d/.containerID
            ;;
            exec)
                if [[ -e "$Tools4Dev_PATH/.t4d/.containerID" ]]; then
                    docker exec -it $T4D_CONTAINER_ID zsh
                fi
            ;;
            stop)
                if [[ -e "$Tools4Dev_PATH/.t4d/.containerID" ]]; then
                    docker stop $T4D_CONTAINER_ID
                    rm $Tools4Dev_PATH/.t4d/.containerID
                fi
            ;;
        esac
    ;;

    -path|path)
        set -e
        cd $2
        shift
        shift
        if [[ -e $PWD/project.env ]]; then
            source $PWD/project.env &> /dev/null || source $PWD/project.env
        else
            source $Tools4Dev_PATH/tools4Dev.env &> /dev/null || source $Tools4Dev_PATH/tools4Dev.env
        fi
        t4dLoadProjectConf &> /dev/null || t4dLoadProjectConf
        $@
    ;;
    *)
        set -e
        if [[ -e $PWD/project.env ]]; then
            source $PWD/project.env &> /dev/null || source $PWD/project.env
        else
            source $Tools4Dev_PATH/tools4Dev.env &> /dev/null || source $Tools4Dev_PATH/tools4Dev.env
        fi
        t4dLoadProjectConf &> /dev/null || t4dLoadProjectConf
        $@
    ;;
esac
